### ISSUE TITLE
Should inline support POJO's?

### ISSUE THREAD

**Issue by JAForbes** [barneycarroll/mithril-machine-tools#16]
In the mithril docs we've decided that pojo's should only be used for stateless components, closures for stateful.

Seeing as the justification for Inline is to have some *state* inline.  It seems we could take that as an opportunity to only support closures.

What do you think?

**Comment by barneycarroll** [comment]
This thing consciously perpetuates bad ideas along with good. Class definition is left out because there’s literally no point, the rest is a series of footguns I’m happy to autopsy.
